server:
  port: 8082
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://192.168.1.107:3306/blog_service?characterEncoding=UTF-8&allowMultiQueries=true&useTimeZone=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ljw.blogservice.domain